---
title: ''
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

options(scipen = 999)

library(tidyverse)
library(tidytuesdayR)
library(here)
# library(janitor)
library(extrafont)
# library(scales)
# library(ggsci)
# library(ggtext)
# library(patchwork)
library(grid)
library(pBrackets)

here::i_am("21-0216_DeBois_Challenge/21-0216_debois_challenge.Rmd")

```

## Get Data

```{r get data}
tt <- tidytuesdayR::tt_load("2021", week = 8)

georgia_pop <- tt$georgia_pop

```

## Clean

Pivot longer

```{r}
georgia_pop <- 
  georgia_pop %>% 
  pivot_longer(cols = Colored:White) %>% 
  mutate(name = str_to_upper(name))
```


## Investigate

```{r}
```

## Wrangle

```{r}

```


## Plot

```{r}
plot_color = "#e1cfb7"

georgia_pop %>% 
  ggplot(aes(x = Year, y = value)) + 
  # geom_line(aes(linetype = name)) +
  geom_line(data = filter(georgia_pop, name == "COLORED"), aes(linetype = str_c("  =  COLORED", "                                                        "))) +
  geom_line(data = filter(georgia_pop, name == "WHITE"), aes(linetype = "  =  WHITE")) +
  scale_linetype_manual(values = c(1, 5)) +
  scale_y_reverse(breaks = seq(0, 100, 5), 
                  minor_breaks = NULL, 
                  expand = expansion()) +
  scale_x_continuous(breaks = seq(1790, 1900, 10), 
                     minor_breaks = NULL, 
                     expand= expansion()) + 
  coord_flip() + 
  labs(x = NULL, 
       y = "PERCENTS",
       title = "COMPARATIVE INCREASE OF WHITE AND COLORED\nPOPULATION IN GEORGIA",
       linetype = NULL) +
  theme(axis.ticks = element_blank(), 
        axis.text.x = element_text(margin = margin(t = 5)), 
        axis.text.y = element_text(margin = margin(r = 5)), 
        axis.title.x = element_text(margin = margin(t = 25), size = 7),
        legend.position = "bottom", 
        legend.background = element_rect(fill = "plot_color"),
        legend.key = element_rect(fill = "plot_color"), 
        legend.key.width = unit(2.5, "cm"),
        plot.background = element_rect(fill = "plot_color", color = "plot_color"), 
        panel.background = element_rect(fill = "plot_color", color = "plot_color"), 
        panel.grid = element_line(color = "#d39b79"), 
        panel.border = element_rect(color = "black", fill = NA), 
        plot.title = element_text(hjust = 0.5, margin = margin(b = 20, t = 20), 
                                  family = "Liberation Sans", size = 13, face = "bold"),
        text = element_text(family = "Liberation Sans Narrow", size = 9), 
        plot.margin = unit(rep(5, 4), "mm"), 
        aspect.ratio = 1.4
  )  


# use grid locator to help get idea of where brackets should go
# grid.locator()


y_pos <- 365
grid.brackets(x1 = 238, y1 = y_pos, 
              x2 = 572, y2 = y_pos, 
              h = -0.0425, curvature = 0.1)


```


## Save plot 

Due to the complexity of this plot, particularly with regards to its aspect ratio and the placement of the braces at the bottom, I manually saved the plot out. 

```{r save plot, eval=FALSE}
dte <- "21-0216"

# ggsave(plot = plot_final,
#        filename = here("21-0216_DuBois_Challenge/output", str_c(dte, "challenge1_georgia_pop.jpeg")),
#        dpi = "retina",
#        device = "jpeg"
#        # height = 4,
#        # width = 4 * 1.618,
#        # units = "in"
# )
# 

```


